import { FAQ, VIPLevel } from "@/app/interface/vip-level";

export const vipLevels: VIPLevel[] = [
  {
    id: "vip1",
    name: "VIP 1",
    color: "bg-white border-b",
    bgColor: "bg-gray-50",
    borderColor: "border-gray-200",
    textColor: "text-gray-900",
    iconColor: "text-gray-700",
    headerTextColor: "text-gray-900",
    headerSubTextColor: "text-gray-500",
    headerIconBg: "bg-gray-100",
    isLightHeader: true,
    deposit: "15,000 USDT",
    reward: "1,500 USDT",
    profitPoint: "25%",
    dailyTraffic: "3,000-5,000",
    featureKeys: [
      "vip1Feature1",
      "vip1Feature2",
      "vip1Feature3",
      "vip1Feature4",
    ],
  },
  {
    id: "vip2",
    name: "VIP 2",
    color: "from-purple-400 to-purple-600",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    textColor: "text-purple-700",
    iconColor: "text-purple-500",
    deposit: "30,000 USDT",
    reward: "3,000 USDT",
    profitPoint: "30%",
    dailyTraffic: "5,000-8,000",
    featureKeys: [
      "vip2Feature1",
      "vip2Feature2",
      "vip2Feature3",
      "vip2Feature4",
    ],
    popular: true,
  },
  {
    id: "vip3",
    name: "VIP 3",
    color: "from-orange-400 to-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    textColor: "text-orange-700",
    iconColor: "text-orange-500",
    deposit: "45,000 USDT",
    reward: "4,500 USDT",
    profitPoint: "35%",
    dailyTraffic: "8,000-11,000",
    featureKeys: [
      "vip3Feature1",
      "vip3Feature2",
      "vip3Feature3",
      "vip3Feature4",
      "vip3Feature5",
    ],
  },
];

export const faqs: FAQ[] = [
  {
    id: "offer",
    questionKey: "faqOffer",
    answerKey: "faqOfferAnswer",
  },
  {
    id: "sales",
    questionKey: "faqSales",
    answerKey: "faqSalesAnswer",
  },
  {
    id: "delivery",
    questionKey: "faqDelivery",
    answerKey: "faqDeliveryAnswer",
  },
  {
    id: "product",
    questionKey: "faqProduct",
    answerKey: "faqProductAnswer",
  },
  {
    id: "upgrade",
    questionKey: "faqUpgrade",
    answerKey: "faqUpgradeAnswer",
  },
];
